# -*- coding: utf-8 -*-
"""portofolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjnITGv7rMt5tvdDA3RkvdRbe_gi6DeJ

cleaning and visualization of West Java forecast data
"""

# Open file and read file

import pandas as pd
df = pd.read_csv('/content/kecamatanforecast-jawabarat.csv')
print(df)

# displays the last 5 rows

print(df.tail(5))

# find missing values

print(df.isnull().sum())

# Removes all columns that have missing values

df = df.dropna(axis=1)

# find duplicate

df = (df.duplicated())
print(df)

# weather data

data = {
    'Date': pd.date_range('2024-01-01', periods=100),
    'Temperature': np.random.randint(20, 35, 100),
    'Humidity': np.random.randint(40, 80, 100)
}
df = pd.DataFrame(data)

# Temperature and humidity time plot

plt.figure(figsize=(10, 6))
plt.plot(df['Date'], df['Temperature'], marker='o', linestyle='-', color='c', label='Temperature (C)')
plt.plot(df['Date'], df['Humidity'], marker='o', linestyle='-', color='g', label='Humidity (%)')
plt.xlabel('Date')
plt.ylabel('Value')
plt.title('Temperature and Humidity over Time')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()